version: '3.8'

services:
  login_app:
    build: .
    container_name: login_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:123456@mongodb:27017/api_login?authSource=admin
      - JWT_SECRET=supersecretkey
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    external: true
